# This is a basic workflow to help you get started with Actions

name: rebuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch, repository_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '12'
      - name: NPM Install
        run: npm i
      - name: Build
        run: |
          node ./index.js -t ./README_template.md -f https://www.ianmccall.codes/feed.xml -o README.md
      - name: Commit and Push
        run: |
          git config user.name "README-bot"
          git config user.email "gitbot@ianmccall.codes"
          git add -A
          git commit -m "README auto updated" || exit 0
          git push
